name: src
description: Psychiatry-UK Patient Portal Mobile App.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.5+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  intl: ^0.17.0
  url_launcher: ^6.2.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  dio: ^5.3.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.4
  bloc: ^8.1.2
  change_app_package_name: ^1.1.0
  webview_flutter: ^4.4.2
  quickalert: ^1.0.2
  jwt_decode: ^0.3.1
  flutter_switch: ^0.3.2
  flutter_native_splash: ^2.3.6
  http: ^1.1.0
  socket_io_client: ^2.0.3
  image_picker: ^1.0.5
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^16.3.0
  http_parser: ^4.0.2
  mime: ^1.0.4
  local_auth: ^2.1.8
  motion_toast: ^2.7.10
  flutter_secure_storage: ^9.0.0
  flutter_jailbreak_detection: ^1.10.0
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.15

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#FFFFFF"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/logo_web-2018.png
    - assets/icon/
    - assets/images/psychiatry-uk-logo.png
    - assets/images/app_icons/Appointments.png
    - assets/images/app_icons/Appointments-White.png
    - assets/images/app_icons/Forms.png
    - assets/images/app_icons/Forms-White.png
    - assets/images/app_icons/Home-White.png
    - assets/images/app_icons/Unread-notes.png
    - assets/images/app_icons/Unread-notes-White.png
    - assets/images/app_icons/Your-Account.png
    - assets/images/app_icons/Urgent.png
    - assets/images/app_icons/Staff-Portal.png
    - assets/images/app_icons/Rate-and-Review.png
    - assets/images/app_icons/Past-Appointments.png
    - assets/images/app_icons/P-UK-ID.png
    - assets/images/app_icons/Notification-Settings.png
    - assets/images/app_icons/Name.png
    - assets/images/app_icons/Help.png
    - assets/images/app_icons/FAQs.png
    - assets/images/app_icons/Email.png
    - assets/images/app_icons/Completed-Froms.png
    - assets/images/app_icons/Call.png
    - assets/images/app_icons/date_icon.png
    - assets/images/app_icons/doctor_icon.png
    - assets/images/app_icons/duration_icon.png
    - assets/images/app_icons/treatment_type_icon.png
    - assets/images/app_icons/type_icon.png
    - assets/images/app_icons/where_icon.png
    - assets/certificate/certificate.pem
    - assets/certificate/companionCert.txt
    - assets/certificate/dynamicCertificate.txt

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/RalewayBold.ttf
          weight: 700
        - asset: assets/fonts/RalewayMedium.ttf
          weight: 500
        - asset: assets/fonts/RalewayRomanExtraBold.ttf
          weight: 800
        - asset: assets/fonts/RalewayRegular.ttf
          weight: 400
        - asset: assets/fonts/RalewaySemiBold.ttf
          weight: 600
        - asset: assets/fonts/RalewayRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/RalewayRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RalewayRomanBold.ttf
          weight: 700
        - asset: assets/fonts/RalewayRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/RalewayExtraBold.ttf
          weight: 800
    - family: Montserrat
      fonts:
        - asset: assets/fonts/MontserratBold.ttf
          weight: 700
        - asset: assets/fonts/MontserratRegular.ttf
          weight: 400
        - asset: assets/fonts/MontserratExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MontserratSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MontserratMedium.ttf
          weight: 500
