name: Generate Android Release and Submit for Aproval
on:  
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:
jobs:

  version:
    name: Version Number
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Retrieve Tags and Branch History
        run: |
          git config remote.origin.url @github.com/${{github.repository">https://x-access-token:${{secrets.TOKEN_GITHUB}}@github.com/${{github.repository}}
          git fetch --prune --depth=10000
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Creating version.txt with nuGetVersion
        run: echo ${{steps.gitversion.outputs.nuGetVersion}} > version.txt
      - name: Upload version.txt
        uses: actions/upload-artifact@v2
        with:
          name: gitversion
          path: version.txt

  build:   
    runs-on: ubuntu-latest    
    steps:      
      - uses: actions/checkout@v4      
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17.x"
          cache: 'gradle'
          
      - uses: subosito/flutter-action@v2
        with:          
          flutter-version: "3.16.9"
          channel: 'stable'
          cache: true
          
      - name: Get dependencies
        working-directory: ./src
        run: flutter pub get

      - name: Create upload-keystore.jks file
        working-directory: ./src
        run: |
          echo "${{ secrets.JKS_B64 }}" | base64 --decode > android/app/upload-keystore.jks
          echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties

      - name: Start release build
        working-directory: ./src
        run: flutter build apk --release
        
      - uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: src/build/app/outputs/flutter-apk/app-release.apk

