name: Generate Android Release and Submit for Aproval
on:  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  version:
    name: Version Number
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Feth Histories for All Tags and Branches
        run: |
          git config remote.origin.url https://x-access-token:${{ secrets.TOKEN_GITHUB }}@github.com/${{ github.repository }}
          git fetch --prune --depth=10000      
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Creating version.txt with nuGetVersion
        run: echo ${{steps.gitversion.outputs.nuGetVersion}} > version.txt
      - name: Upload version.txt
        uses: actions/upload-artifact@v2
        with:
          name: gitversion
          path: version.txt

  build:   
    runs-on: ubuntu-latest 
    needs: [version]
    steps:      
      - uses: actions/checkout@v4  
      - name: Get version.txt
        uses: actions/download-artifact@v2
        with:
          name: gitversion  
          
      - name: Create New File Without Newline Char from version.txt
        run: tr -d '\n' < version.txt > version1.txt
      - name: Read Version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: version1.txt
      - name: Update Version in YAML
        run: sed -i 's/99.99.99+99/${{ steps.version.outputs.content }}+${{ github.run_number }}/g' src/pubspec.yaml
        
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17.x"
          cache: 'gradle'
          
      - uses: subosito/flutter-action@v2
        with:          
          flutter-version: "3.16.9"
          channel: 'stable'
          cache: true
          
      - name: Clear project
        working-directory: ./src        
        run: flutter clean
      - name: Get dependencies
        working-directory: ./src        
        run: flutter pub get

      - name: Create upload-keystore.jks file
        working-directory: ./src
        run: |
          echo "${{ secrets.JKS_B64 }}" | base64 --decode > android/app/upload-keystore.jks
          echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties

      - name: Start and Generate App Bundle
        working-directory: ./src        
        run: flutter build appbundle 
        
      - name: Upload App Bundle and ready to submit 
        uses: actions/upload-artifact@v4
        with:
          name: appbundle
          path: src/build/app/outputs/bundle/release/app-release.aab
          
  release:
    name: Release app to production track
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get appbundle from artifacts
      uses: actions/download-artifact@v2
      with:
        name: appbundle
    - name: Release app to production track
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{secrets.PLAYSTORE_ACCOUNT_KEY}}
        packageName: com.psychiatryuk.src
        releaseFiles: app-release.aab
        track: production
        status: completed

