name: Generate Android Release
on:  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
jobs:
  build:   
    runs-on: ubuntu-latest    
    steps:      
      - uses: actions/checkout@v4      
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
          
      - uses: subosito/flutter-action@v2
        with:          
          flutter-version: "3.16.9"
          channel: 'stable'
          cache: true
          
      - name: Get dependencies
        working-directory: ./src
        run: flutter pub get

      - name: Create upload-keystore.jks file
        working-directory: ./src
        run: |
          echo "${{ secrets.JKS_B64 }}" | base64 --decode > android/app/upload-keystore.jks
          echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties

      - name: Start release build
        working-directory: ./src
        run: flutter build apk --release

